//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dotNet_Client.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.m0hamedAit.ma/", ConfigurationName="ServiceReference1.BankService")]
    public interface BankService {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.m0hamedAit.ma/BankService/ConvertRequest", ReplyAction="http://ws.m0hamedAit.ma/BankService/ConvertResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        dotNet_Client.ServiceReference1.ConvertResponse Convert(dotNet_Client.ServiceReference1.ConvertRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.m0hamedAit.ma/BankService/ConvertRequest", ReplyAction="http://ws.m0hamedAit.ma/BankService/ConvertResponse")]
        System.Threading.Tasks.Task<dotNet_Client.ServiceReference1.ConvertResponse> ConvertAsync(dotNet_Client.ServiceReference1.ConvertRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.m0hamedAit.ma/BankService/listAccountsRequest", ReplyAction="http://ws.m0hamedAit.ma/BankService/listAccountsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        dotNet_Client.ServiceReference1.listAccountsResponse listAccounts(dotNet_Client.ServiceReference1.listAccountsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.m0hamedAit.ma/BankService/listAccountsRequest", ReplyAction="http://ws.m0hamedAit.ma/BankService/listAccountsResponse")]
        System.Threading.Tasks.Task<dotNet_Client.ServiceReference1.listAccountsResponse> listAccountsAsync(dotNet_Client.ServiceReference1.listAccountsRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.m0hamedAit.ma/BankService/getAccountRequest", ReplyAction="http://ws.m0hamedAit.ma/BankService/getAccountResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        dotNet_Client.ServiceReference1.getAccountResponse getAccount(dotNet_Client.ServiceReference1.getAccountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.m0hamedAit.ma/BankService/getAccountRequest", ReplyAction="http://ws.m0hamedAit.ma/BankService/getAccountResponse")]
        System.Threading.Tasks.Task<dotNet_Client.ServiceReference1.getAccountResponse> getAccountAsync(dotNet_Client.ServiceReference1.getAccountRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Convert", WrapperNamespace="http://ws.m0hamedAit.ma/", IsWrapped=true)]
    public partial class ConvertRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.m0hamedAit.ma/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double amount;
        
        public ConvertRequest() {
        }
        
        public ConvertRequest(double amount) {
            this.amount = amount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConvertResponse", WrapperNamespace="http://ws.m0hamedAit.ma/", IsWrapped=true)]
    public partial class ConvertResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.m0hamedAit.ma/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double @return;
        
        public ConvertResponse() {
        }
        
        public ConvertResponse(double @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.m0hamedAit.ma/")]
    public partial class account : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codeField;
        
        private System.DateTime dateCreationField;
        
        private bool dateCreationFieldSpecified;
        
        private double soldeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime dateCreation {
            get {
                return this.dateCreationField;
            }
            set {
                this.dateCreationField = value;
                this.RaisePropertyChanged("dateCreation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dateCreationSpecified {
            get {
                return this.dateCreationFieldSpecified;
            }
            set {
                this.dateCreationFieldSpecified = value;
                this.RaisePropertyChanged("dateCreationSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public double solde {
            get {
                return this.soldeField;
            }
            set {
                this.soldeField = value;
                this.RaisePropertyChanged("solde");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listAccounts", WrapperNamespace="http://ws.m0hamedAit.ma/", IsWrapped=true)]
    public partial class listAccountsRequest {
        
        public listAccountsRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listAccountsResponse", WrapperNamespace="http://ws.m0hamedAit.ma/", IsWrapped=true)]
    public partial class listAccountsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.m0hamedAit.ma/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public dotNet_Client.ServiceReference1.account[] @return;
        
        public listAccountsResponse() {
        }
        
        public listAccountsResponse(dotNet_Client.ServiceReference1.account[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAccount", WrapperNamespace="http://ws.m0hamedAit.ma/", IsWrapped=true)]
    public partial class getAccountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.m0hamedAit.ma/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int code;
        
        public getAccountRequest() {
        }
        
        public getAccountRequest(int code) {
            this.code = code;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAccountResponse", WrapperNamespace="http://ws.m0hamedAit.ma/", IsWrapped=true)]
    public partial class getAccountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.m0hamedAit.ma/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public dotNet_Client.ServiceReference1.account @return;
        
        public getAccountResponse() {
        }
        
        public getAccountResponse(dotNet_Client.ServiceReference1.account @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BankServiceChannel : dotNet_Client.ServiceReference1.BankService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BankServiceClient : System.ServiceModel.ClientBase<dotNet_Client.ServiceReference1.BankService>, dotNet_Client.ServiceReference1.BankService {
        
        public BankServiceClient() {
        }
        
        public BankServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BankServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BankServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BankServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        dotNet_Client.ServiceReference1.ConvertResponse dotNet_Client.ServiceReference1.BankService.Convert(dotNet_Client.ServiceReference1.ConvertRequest request) {
            return base.Channel.Convert(request);
        }
        
        public double Convert(double amount) {
            dotNet_Client.ServiceReference1.ConvertRequest inValue = new dotNet_Client.ServiceReference1.ConvertRequest();
            inValue.amount = amount;
            dotNet_Client.ServiceReference1.ConvertResponse retVal = ((dotNet_Client.ServiceReference1.BankService)(this)).Convert(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<dotNet_Client.ServiceReference1.ConvertResponse> dotNet_Client.ServiceReference1.BankService.ConvertAsync(dotNet_Client.ServiceReference1.ConvertRequest request) {
            return base.Channel.ConvertAsync(request);
        }
        
        public System.Threading.Tasks.Task<dotNet_Client.ServiceReference1.ConvertResponse> ConvertAsync(double amount) {
            dotNet_Client.ServiceReference1.ConvertRequest inValue = new dotNet_Client.ServiceReference1.ConvertRequest();
            inValue.amount = amount;
            return ((dotNet_Client.ServiceReference1.BankService)(this)).ConvertAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        dotNet_Client.ServiceReference1.listAccountsResponse dotNet_Client.ServiceReference1.BankService.listAccounts(dotNet_Client.ServiceReference1.listAccountsRequest request) {
            return base.Channel.listAccounts(request);
        }
        
        public dotNet_Client.ServiceReference1.account[] listAccounts() {
            dotNet_Client.ServiceReference1.listAccountsRequest inValue = new dotNet_Client.ServiceReference1.listAccountsRequest();
            dotNet_Client.ServiceReference1.listAccountsResponse retVal = ((dotNet_Client.ServiceReference1.BankService)(this)).listAccounts(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<dotNet_Client.ServiceReference1.listAccountsResponse> dotNet_Client.ServiceReference1.BankService.listAccountsAsync(dotNet_Client.ServiceReference1.listAccountsRequest request) {
            return base.Channel.listAccountsAsync(request);
        }
        
        public System.Threading.Tasks.Task<dotNet_Client.ServiceReference1.listAccountsResponse> listAccountsAsync() {
            dotNet_Client.ServiceReference1.listAccountsRequest inValue = new dotNet_Client.ServiceReference1.listAccountsRequest();
            return ((dotNet_Client.ServiceReference1.BankService)(this)).listAccountsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        dotNet_Client.ServiceReference1.getAccountResponse dotNet_Client.ServiceReference1.BankService.getAccount(dotNet_Client.ServiceReference1.getAccountRequest request) {
            return base.Channel.getAccount(request);
        }
        
        public dotNet_Client.ServiceReference1.account getAccount(int code) {
            dotNet_Client.ServiceReference1.getAccountRequest inValue = new dotNet_Client.ServiceReference1.getAccountRequest();
            inValue.code = code;
            dotNet_Client.ServiceReference1.getAccountResponse retVal = ((dotNet_Client.ServiceReference1.BankService)(this)).getAccount(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<dotNet_Client.ServiceReference1.getAccountResponse> dotNet_Client.ServiceReference1.BankService.getAccountAsync(dotNet_Client.ServiceReference1.getAccountRequest request) {
            return base.Channel.getAccountAsync(request);
        }
        
        public System.Threading.Tasks.Task<dotNet_Client.ServiceReference1.getAccountResponse> getAccountAsync(int code) {
            dotNet_Client.ServiceReference1.getAccountRequest inValue = new dotNet_Client.ServiceReference1.getAccountRequest();
            inValue.code = code;
            return ((dotNet_Client.ServiceReference1.BankService)(this)).getAccountAsync(inValue);
        }
    }
}
